---
# tasks specific to creating a new network and maybe deleting the old

- name: config_network| define network based on template
  become: yes
  virt_net:
    command: define
    name: "{{ libvirt_network.name }}"
    xml: "{{ lookup('template', 'new_network.xml.j2') }}"

- name: config_network| activate {{ libvirt_network.name }} network
  become: yes
  virt_net:
    name: "{{ libvirt_network.name }}"
    state: active
    autostart: yes

- name: config_network| set {{ libvirt_network.name }} network to autostart
  become: yes
  virt_net:
    name: "{{ libvirt_network.name }}"
    autostart: yes

- name: config_network| remove default network if specified
  block:
    - name: config_network| stop the default network
      become: yes
      virt_net:
        state: inactive
        name: default

    - name: config_network| delete the default network
      become: yes
      virt_net:
        command: undefine
        name: default
  when: libvirt_network.remove_default