---
# tasks specific to creating a new storage pool and maybe deleting the old

- name: Config_storage| ensure new pool directory exists
  ansible.builtin.file:
    path: "{{ libvirt_storage.pool_location }}"
    state: directory
    mode: "0644"
  become: true

- name: Config_storage| when the default pool will be replaced
  when: libvirt_storage.replace_default
  block:
    - name: Config_storage| get ansible_libvirt_pools facts
      virt_pool:
        command: facts
      become: true

    - name: Config_storage| destroy the default pool
      virt_pool:
        command: destroy
        name: default
      when: ansible_libvirt_pools.default is defined and ansible_libvirt_pools.default.state == "active"
      register: destroyed
      become: true

    - name: Config_storage| populate ansible_libvirt_pools facts again
      virt_pool:
        command: facts
      when: destroyed is successful
      become: true

    - name: Config_storage| delete the default pool so we don't fill up /
      virt_pool:
        command: undefine
        name: default
      when: ansible_libvirt_pools.default is defined and ansible_libvirt_pools.default.state == "inactive"
      # variable precedence requires these shenanigans
      become: true

    - name: Config_storage| set default_pool_file
      ansible.builtin.set_fact:
        default_pool_file: default_pool.xml.j2
        default_name: default

- name: Config_storage| set storage_pool_file
  ansible.builtin.set_fact:
    storage_pool_file: "{{ default_pool_file | default('new_pool.xml.j2') }}"
    new_name: "{{ default_name | default(libvirt_storage.pool_name) }}"
- name: Config_storage| refresh ansible_libvirt_pools facts
  virt_pool:
    command: facts
  become: true
- name: Config_storage| define storage pool based on template
  virt_pool:
    name: "{{ new_name }}"
    command: define
    xml: "{{ lookup('template', storage_pool_file) }}"
  #   when: ansible_libvirt_pools.new_name is not defined
  # - name: config_storage| refresh ansible_libvirt_pools facts again
  #   become: yes
  #   virt_pool:
  #     command: facts
  # - name: debugging
  #   debug:
  #     msg: "{{ new_name }} {{ ansible_libvirt_pools.new_name }}"
  become: true
- name: Config_storage| activate {{ new_name }} storage pool
  virt_pool:
    name: "{{ new_name }}"
    state: active
    autostart: true
  become: true
- name: Config_storage| set {{ new_name }} to autostart
  virt_pool:
    name: "{{ new_name }}"
    autostart: true
  # I'm not sure what will happen if the default pool somehow has something it it
  # NOTE: just starting virt-manager regenerates the default pool...is there
  #       somewhere else to remove it?
  become: true
