---
# apply user configuration so a non-root user can access libvirtd easily
#  user = new_user

- name: Config_user| create the libvirt system group
  ansible.builtin.group:
    name: libvirt
    state: present
  become: true

- name: Config_user| add {{ user }} to libvirt group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: libvirt
    append: true
  become: true

- name: Config_user| remove any existing LIBVIRT_DEFAULT_URI from .bashrc [{{ user }}]
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    regexp: LIBVIRT_DEFAULT_URI
    state: absent
    mode: "0644"
  become: true
  become_user: "{{ user }}"

- name: Config_user| add the URI we want back to .bashrc [{{ user }}]
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: export LIBVIRT_DEFAULT_URI="qemu:///system"
    create: true
    mode: "0644"
  become: true
  become_user: "{{ user }}"
