---
# modify some configurations

# - name: config| create the libvirt system group
#   become: yes
#   group:
#     name: libvirt
#     state: present

# - name: config| add new_user to libvirt group
#   become: yes
#   user:
#     name: "{{ new_user | default( ansible_user_id ) }}"
#     groups: libvirt

- include_tasks: config_for_sat.yml
  when: config_for_sat

- include_tasks: config_storage.yml
  when: libvirt_storage.pool_name is defined and
        libvirt_storage.pool_location is defined

- include_tasks: config_network.yml
  when: libvirt_network.name is defined and
        libvirt_network.bridge_name is defined and
        libvirt_network.ip_address is defined
