---
# install some packages and utilities

- name: install| libvirtd tools and utilities
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt-client
    - libguestfs-tools
    - virt-manager
    - virt-install

- name: install| install Python modules
  become: true
  pip:
    name: ['lxml']
    state: present