---
# install some packages and utilities

- name: install| libvirtd tools and utilities
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt-client
    - libguestfs-tools
    - cockpit
    - cockpit-machines
    - virt-install

- name: install| install Python modules
  become: true
  pip:
    name: ['lxml']
    state: present

- name: install| start services
  become: true
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - libvirtd
    - cockpit.socket
