---
# install some packages and utilities

- name: Install| libvirtd tools and utilities
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - libvirt-client
    - libguestfs-tools
    - cockpit
    - cockpit-machines
    - virt-install
  become: true

- name: Install| install Python modules
  ansible.builtin.pip:
    name: [lxml]
    state: present
  become: true

- name: Install| start services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - libvirtd
    - cockpit.socket
  become: true
