---
# main tasks file for spideroak role
#  http://blog.stillwell.me/blog/2015/06/09/multi-environment-deployments-with-ansible/

- name: main | Set ansible_distro variable
  ansible.builtin.set_fact:
    ansible_distro: "{{ ansible_distribution | lower | replace('\"', '') }}"
  when: ansible_distro is not defined
  tags: always

- name: main | Gather os specific variables for role
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distro }}-{{ ansible_distribution_version | lower | replace('/', '_') }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distribution_major_version | lower | replace('/', '_') }}.yml"
        - "{{ ansible_distro }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: always

- ansible.builtin.include_tasks: install.yml

- ansible.builtin.include_tasks: config.yml
  when: ansible_distro == "fedora"
